# Default packit instance is a prod and only this is used
# stg instance is present for testing new packit features in forked repositories where stg is installed.
packit_instances: ["prod", "stg"]
upstream_project_url: https://github.com/strimzi/strimzi-kafka-operator
issue_repository: https://github.com/strimzi/strimzi-kafka-operator
jobs:
  - job: tests
    trigger: pull_request
    # Suffix for job name
    identifier: "automation-check"
    targets:
      # This target is not used at all by our tests, but it has to be one of the available - https://packit.dev/docs/configuration/#aliases
      - centos-stream-9-x86_64
      - centos-stream-9-aarch64
    # We don't need to build any packages for Fedora/RHEL/CentOS, it is not related to Strimzi tests
    skip_build: true
    manual_trigger: true
    env: { IP_FAMILY: ipv4 }
    labels:
      - smoke
      - automation-check
    tf_extra_params:
      test:
        tmt:
          name: smoke
  ###############################################################################################

  - job: tests
    trigger: pull_request
    identifier: "upgrade"
    targets:
      - centos-stream-9-x86_64
      - centos-stream-9-aarch64
    skip_build: true
    manual_trigger: true
    env: { IP_FAMILY: ipv4 }
    labels:
      - upgrade
    tf_extra_params:
      test:
        tmt:
          name: upgrade
  ###############################################################################################

  - job: tests
    trigger: pull_request
    identifier: "regression-operators"
    targets:
      - centos-stream-9-x86_64
      - centos-stream-9-aarch64
    skip_build: true
    manual_trigger: true
    env: { IP_FAMILY: ipv4 }
    labels:
      - regression
      - operators
      - regression-operators
    tf_extra_params:
      test:
        tmt:
          name: regression-operators
  ###############################################################################################

  - job: tests
    trigger: pull_request
    identifier: "regression-brokers-and-security"
    targets:
      - centos-stream-9-x86_64
      - centos-stream-9-aarch64
    skip_build: true
    manual_trigger: true
    env: { IP_FAMILY: ipv4 }
    labels:
      - regression
      - brokers-and-security
      - regression-brokers-and-security
      - bas
    tf_extra_params:
      test:
        tmt:
          name: regression-brokers-and-security

  - job: tests
    trigger: pull_request
    identifier: "regression-operands"
    targets:
      - centos-stream-9-x86_64
      - centos-stream-9-aarch64
    skip_build: true
    manual_trigger: true
    env: { IP_FAMILY: ipv4 }
    labels:
      - regression
      - operands
      - regression-operands
    tf_extra_params:
      test:
        tmt:
          name: regression-operands
  ###############################################################################################

  - job: tests
    trigger: pull_request
    identifier: "acceptance"
    targets:
      - centos-stream-9-x86_64
      - centos-stream-9-aarch64
    skip_build: true
    manual_trigger: true
    env: { IP_FAMILY: ipv4 }
    labels:
      - acceptance
    tf_extra_params:
      test:
        tmt:
          name: acceptance
  ###############################################################################################

  - job: tests
    trigger: pull_request
    identifier: "sanity"
    targets:
      - centos-stream-9-x86_64
      - centos-stream-9-aarch64
    skip_build: true
    manual_trigger: true
    env: { IP_FAMILY: ipv4 }
    labels:
      - sanity
    tf_extra_params:
      test:
        tmt:
          name: sanity

  ###############################################################################################
  ##################################    IPv6/dual jobs   ########################################
  ###############################################################################################
  - job: tests
    trigger: pull_request
    identifier: "acceptance_ipv6"
    targets:
      - centos-stream-9-x86_64
      - centos-stream-9-aarch64
    skip_build: true
    manual_trigger: true
    env: { IP_FAMILY: ipv6 }
    labels:
      - acceptance_ipv6
      - ipv6
    tf_extra_params:
      test:
        tmt:
          name: acceptance
  ###############################################################################################
  - job: tests
    trigger: pull_request
    identifier: "acceptance_dual"
    targets:
      - centos-stream-9-x86_64
      - centos-stream-9-aarch64
    skip_build: true
    manual_trigger: true
    env: { IP_FAMILY: dual }
    labels:
      - acceptance_dual
      - dual
    tf_extra_params:
      test:
        tmt:
          name: acceptance
  ###############################################################################################
  ####################################    Performance   #########################################
  ###############################################################################################
  - job: tests
    trigger: pull_request
    identifier: "performance"
    targets:
      - centos-stream-9-x86_64
      - centos-stream-9-aarch64
    skip_build: true
    manual_trigger: true
    env: { IP_FAMILY: ipv4 }
    labels:
      - performance
      - performance-common
    tf_extra_params:
      settings:
        pipeline:
          timeout: 1440
      test:
        tmt:
          name: performance
  - job: tests
    trigger: pull_request
    identifier: "performance-capacity"
    targets:
      - centos-stream-9-x86_64
      - centos-stream-9-aarch64
    skip_build: true
    manual_trigger: true
    env: { IP_FAMILY: ipv4 }
    labels:
      - performance
      - performance-capacity
    tf_extra_params:
      settings:
        pipeline:
          timeout: 1440
      test:
        tmt:
          name: performance-capacity
  - job: tests
    trigger: pull_request
    identifier: "performance-topic-operator-capacity"
    targets:
      - centos-stream-9-x86_64
      - centos-stream-9-aarch64
    skip_build: true
    manual_trigger: true
    env: { IP_FAMILY: ipv4 }
    labels:
      - performance
      - performance-topic-operator-capacity
    tf_extra_params:
      settings:
        pipeline:
          timeout: 1440
      test:
        tmt:
          name: performance-topic-operator-capacity
